
set TURTLEBOT2_WIN10_PATH=%~dp0
set ROS2_PATH=%TURTLEBOT2_WIN10_PATH%..\ros2

type NUL > %TURTLEBOT2_WIN10_PATH%\ecl_core\AMENT_IGNORE
type NUL > %TURTLEBOT2_WIN10_PATH%\ecl_lite\AMENT_IGNORE
type NUL > %TURTLEBOT2_WIN10_PATH%\ecl_navigation\AMENT_IGNORE
type NUL > %TURTLEBOT2_WIN10_PATH%\kobuki\AMENT_IGNORE
type NUL > %TURTLEBOT2_WIN10_PATH%\kobuki_core\AMENT_IGNORE
type NUL > %TURTLEBOT2_WIN10_PATH%\sophus\AMENT_IGNORE

type NUL > %ROS2_PATH%\poco_vendor\AMENT_IGNORE
